language: node_js
node_js:
- lts/*
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: NNP5oGE2MbR9Daf+4rLZm/kSH1uFSdE7PDqPbgcWSUxLOXYHySgy7AfeUR1be40DvRRRjOUC7ALkqmhxDvo0wCG/Boe2K89lhbbTN98z8RozgdqVAMPiaJwu/529oTIP/a0GiKOGNG9qa+UNVgCLFvV4k7JSGXRL8KtX/iJnysm8eUhNZ9xK5nFduBj6kFlBr9uIRqt0ojMqfS+qOuaWJ4H/4HAuUvs5KzLOdjYToDZUfmC1SfKcLGvIp/Ah3iX4yTRhn59LA6z2Z/jBsiTpgrtIl0QvZ4AnnZip0yA6UuG8k6gZNVUOSiVb2TN8Zl/1Ocx9BRRbOTs5kefglAuMIu6BxK2qMYP5mfevJcsJAILpPzgc3OnMe39jGSXtkTp1eACK8IR3Xc9zeWIRUHmSWVeNVOZuaJjNI6X2StuPXy01951PGuvddy4JclYCSJvdW35HskTpA5RUnBvJcvYxVkKt6InNxpXIghm32j7S1V2YU0rr+5vJ3CAb3dPG1m1IKp7VK2KZeKmrKuKqvIpxuJwp+kUM7oylCXndsU7Ni5VBEvQ6I/Vgz14gQx2PviJ6vIxWWm55wHKPfw3/Ou4qqh2/rvYjudoiOm3OU2qryOiYuB36H6x+rHrUsLQPa7xfIAn8FcPAEmVhVtwtPIzF23hpjD7rC0VJ23c8UUa+cCc=
  on:
    all_branches: true
    tag: true