language: node_js
node_js:
- lts/*
script:
- npm run lint
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: fHwxPK+2tNZdZlGghTdbjcGfpMgZ8TU15sBkuVKCH4tjlkAM1gr3diWRLDC6etsqph3+ihQZlMi5UImRkC9UMjlqe5XmWAgFhzd4+a4OBQ/UxVU8mNULGntGnY/3kP19f+DB5OyBahatqX4fGTJ9xcz9zKXaxQQTaCox450s+oo9eYVphNX7t473DQBSYjU1V0ryivmZaJbk79aVarMlfdr9DkUJXbDOyw14D0ewS4uWQvGniQ/2gPhIfifib41UcjHtdnSSsB5NQe+tri8b98EHf5Yb9BZuec4eizkUax9Kn7XrLJVTT4XGbzB9CMq6Y4Nj6FNG1QuHAsZ24TZabslWjH49lfVnCuZ9zKJgjxshVa32asoPwH9OSsLLG522vXklDUKbIMfnK+3PzEjhEeH1iXJ25DajQbyakKVvceEHC/a3SZt8Zwh6MszjTmvEHs6RBRVPGLrAu3/iS0p+HvrLejYi4K30vWmBIBZWFsGSutBP6kqKKSpYSwltOLOiYWc5wyeR45kFJ6HCCRszldZhlr8Q6f6zogVWY4kDATwTL25aVg71/QLwSrhFs4ouYtePpo8yhar/hfMhkS7pR2UXOy7WNmeAalroRpri1bPhiOcttdwR65829tds+FpB+1szYFJFp8VM5UfnUs7jdp/baeWgYIBohmy1tAjtnh8=
  on:
    all_branches: true
    tag: true
  edge: true
